apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: promote
spec:
  inputs:
    params:
    - name: github-secret
      type: string
      description: secret name of the github that has the access token. The key name is token.
    - name: from
      type: string
      description: github repository url to be promoted from
    - name: to
      type: string
      description: github repository url to be promoted to
    - name: service
      type: string
      description: service name to be promoted
    - name: commit-name
      type: string
      description: the GitHub username to username
    - name: commit-email
      type: string
      description: the GitHub email to use
  steps:
  - name: promote
    image: quay.io/redhat-developer/gitops-cli
    imagePullPolicy: Always
    script: |
      #!/bin/sh
      services promote --commit-name=$(params.commit-name) --commit-email=$(params.commit-email) --from $(params.from) --to $(params.to) --service $(params.service)
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.github-secret)
          key: token

