apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: service-promote-pipeline-run-
spec:
  resources:
  - name: git-source
    resourceRef:
      name: git-app-repo
  - name: docker-image
    resourceRef:
      name: docker-app-image
  params:
  - name: commitId
    value: v1
  - name: github-secret
    value: promote-secret
  - name: github-config
    value: promote-configmap
  - name: to
    value: "https://github.com/REPLACE_ME.GITHUB_USERNAME/REPLACE_ME.GITHUB_REPO.git"
  - name: service
    value: service-a
  workspaces:
  - name: repo-space
    persistentVolumeClaim:
      claimName: repopvc
  serviceAccountName: demo
  pipelineRef:
    name: service-promote-pipeline
