apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-app-repo
spec:
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/REPLACE_ME.GITHUB_ORG/REPLACE_ME.GITHUB_REPO.git
  type: git

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-app-image
spec:
  params:
  - name: url
    value: REPLACE_ME.DOCKER_USERNAME/REPLACE_ME.DOCKER_IMAGE_NAME
  type: image

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repopvc
spec:
  resources:
    requests:
      storage: 16Mi
  accessModes:
    - ReadWriteOnce
